# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryID', models.CharField(max_length=250)),
                ('categoryName', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ProdId', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('PName', models.CharField(max_length=100, verbose_name='Product Name')),
                ('PType', models.CharField(max_length=250, verbose_name='Product Type')),
                ('PCat', models.CharField(max_length=100, verbose_name='Product Category')),
                ('PPrice', models.CharField(max_length=250, verbose_name='Price')),
                ('Prourl', models.CharField(max_length=500, verbose_name='Product Image URL')),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.CharField(default=uuid.uuid4, max_length=250, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('creditCardNo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=100)),
                ('expirationMonth', models.CharField(max_length=100)),
                ('expirationYear', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('bAddress', models.CharField(max_length=1000)),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderQuantity', models.CharField(max_length=500)),
                ('CurrentQuantity', models.CharField(max_length=500)),
                ('ProBuyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ProdId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='return_order',
            fields=[
                ('ReturnId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('RTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('ReturnReason', models.CharField(choices=[('Product Damaged', 'Product Damaged'), ('Item arrived too late', 'Item arrived too late'), ('Missing Parts or accesories', 'Missing Parts or accesories'), ('Product and shipping box both damaged', 'Product and shipping box both damaged'), ('Wrong item sent', 'Wrong item sent'), ('Item defective', 'Item defective'), ('Item no longer needed', 'Item no longer needed')], max_length=500)),
                ('ReturnOptions', models.CharField(choices=[('Cashback', 'Cashback'), ('Replacement', 'Replacement'), ('EKart Credits', 'EKart Credits')], max_length=500)),
                ('ProductQuality', models.CharField(choices=[('Excellent - Unopened', 'Excellent - Unopened'), ('Good - Slightly Used', 'Good - Slightly Used'), ('Poor - Broken', 'Poor - Broken')], max_length=500)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Product')),
                ('orderid', models.ManyToManyField(to='order.Order')),
            ],
            options={
                'db_table': 'Return Order',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentNo', models.BigIntegerField()),
                ('tOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('tProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Inventory')),
                ('tPurchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Track',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='oCreditCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='oPurchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
