# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='CurrentQuantity',
        ),
        migrations.AddField(
            model_name='product',
            name='sAddress',
            field=models.CharField(default=1, max_length=1000, verbose_name='Shipping Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='OrderQuantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterModelTable(
            name='track',
            table='Track Order',
        ),
    ]
